code fixes ....
Fixed code issues:
```
opcalendar/views.py:2:1: F401 'logging' imported but unused
opcalendar/views.py:9:1: F401 'django.views.generic.UpdateView' imported but unused
opcalendar/views.py:9:1: F401 'django.views.generic.DeleteView' imported but unused
opcalendar/views.py:15:1: F401 'django.urls.reverse_lazy' imported but unused
opcalendar/views.py:27:1: F403 'from .models import *' used; unable to detect undefined names
opcalendar/views.py:41:18: F405 'EveCharacter' may be undefined, or defined from star imports: .models
opcalendar/views.py:45:22: F405 'CharacterOwnership' may be undefined, or defined from star imports: .models
opcalendar/views.py:48:12: F405 'CharacterOwnership' may be undefined, or defined from star imports: .models
opcalendar/views.py:68:27: F405 'EveCorporationInfo' may be undefined, or defined from star imports: .models
opcalendar/views.py:71:16: F405 'EveCorporationInfo' may be undefined, or defined from star imports: .models
opcalendar/views.py:72:27: F405 'EveCorporationInfo' may be undefined, or defined from star imports: .models
opcalendar/views.py:77:24: F405 'Owner' may be undefined, or defined from star imports: .models
opcalendar/views.py:128:13: F405 'Event' may be undefined, or defined from star imports: .models
opcalendar/views.py:138:31: F405 'EventCategory' may be undefined, or defined from star imports: .models
opcalendar/views.py:162:9: F405 'Event' may be undefined, or defined from star imports: .models
opcalendar/views.py:181:37: F405 'reverse' may be undefined, or defined from star imports: .models
opcalendar/views.py:190:13: F405 'Event' may be undefined, or defined from star imports: .models
opcalendar/views.py:210:13: F405 'Event' may be undefined, or defined from star imports: .models
opcalendar/views.py:228:13: F405 'IngameEvents' may be undefined, or defined from star imports: .models
opcalendar/views.py:245:22: F405 'EventMember' may be undefined, or defined from star imports: .models
opcalendar/views.py:246:21: F405 'Event' may be undefined, or defined from star imports: .models
opcalendar/views.py:249:17: F405 'EventMember' may be undefined, or defined from star imports: .models
opcalendar/views.py:264:28: F405 'Event' may be undefined, or defined from star imports: .models
opcalendar/tests.py:1:1: F401 'django.test.TestCase' imported but unused
opcalendar/utils.py:2:1: F401 'logging' imported but unused
opcalendar/utils.py:4:1: F401 'datetime.timedelta' imported but unused
opcalendar/utils.py:6:1: F401 'eventcalendar.helper.get_current_user' imported but unused
opcalendar/utils.py:12:1: F401 'django.utils.translation.ugettext_lazy as _' imported but unused
opcalendar/utils.py:91:15: F541 f-string is missing placeholders
opcalendar/helpers.py:4:1: F401 'django.utils.translation.ugettext_lazy as _' imported but unused
opcalendar/helpers.py:10:9: F841 local variable 'days' is assigned to but never used
opcalendar/apps.py:8:9: F401 'opcalendar.signals' imported but unused
opcalendar/decorators.py:3:1: F401 'allianceauth.services.hooks.get_extension_logger' imported but unused
opcalendar/signals.py:3:1: F401 'django.db.models.signals.pre_save' imported but unused
opcalendar/signals.py:4:1: F401 'allianceauth.groupmanagement.models.GroupRequest' imported but unused
opcalendar/signals.py:5:1: F401 'allianceauth.authentication.models.UserProfile' imported but unused
opcalendar/signals.py:5:1: F401 'allianceauth.authentication.models.CharacterOwnership' imported but unused
opcalendar/signals.py:5:1: F401 'allianceauth.authentication.models.EveCharacter' imported but unused
opcalendar/signals.py:10:1: F401 'allianceauth.eveonline.evelinks.eveimageserver.type_icon_url' imported but unused
opcalendar/signals.py:10:1: F401 'allianceauth.eveonline.evelinks.eveimageserver.character_portrait_url' imported but unused
opcalendar/signals.py:15:1: F401 'requests' imported but unused
opcalendar/signals.py:16:1: F401 'json' imported but unused
opcalendar/signals.py:23:1: F401 '.helpers.time_helpers' imported but unused
opcalendar/signals.py:29:1: E402 module level import not at top of file
opcalendar/signals.py:29:1: F401 'django.utils.translation.ugettext_lazy as _' imported but unused
opcalendar/signals.py:31:1: E402 module level import not at top of file
opcalendar/signals.py:50:8: E713 test for membership should be 'not in'
opcalendar/signals.py:134:17: F841 local variable 'doctrine' is assigned to but never used
opcalendar/signals.py:193:8: E713 test for membership should be 'not in'
opcalendar/signals.py:267:17: F841 local variable 'doctrine' is assigned to but never used
eventcalendar/views.py:3:1: F401 'django.contrib.auth.models.User' imported but unused
opcalendar/admin.py:13:1: F401 'django.utils.translation.ugettext_lazy as _' imported but unused
opcalendar/forms.py:2:1: F401 'django.forms.widgets.TextInput' imported but unused
opcalendar/forms.py:6:1: F401 'django.utils.translation.ugettext_lazy as _' imported but unused
opcalendar/tasks.py:3:1: F401 'django.utils.timezone' imported but unused
opcalendar/tasks.py:6:1: F401 'logging' imported but unused
opcalendar/tasks.py:8:1: F401 'dateutil.parser.parse' imported but unused
opcalendar/tasks.py:17:1: F401 'random' imported but unused
opcalendar/tasks.py:20:1: F811 redefinition of unused 'shared_task' from line 1
opcalendar/tasks.py:23:1: F811 redefinition of unused 'QueueOnce' from line 13
opcalendar/tasks.py:24:1: F401 'esi.models.Token' imported but unused
opcalendar/tasks.py:57:1: E302 expected 2 blank lines, found 1
opcalendar/tasks.py:64:5: F841 local variable 'local_tz' is assigned to but never used
opcalendar/tasks.py:90:21: E265 block comment should start with '# '
opcalendar/tasks.py:94:28: E713 test for membership should be 'not in'
opcalendar/tasks.py:251:42: W605 invalid escape sequence '\('
opcalendar/tasks.py:251:44: W605 invalid escape sequence '\['
opcalendar/tasks.py:251:51: W605 invalid escape sequence '\)'
opcalendar/tasks.py:251:53: W605 invalid escape sequence '\]'
opcalendar/models.py:16:1: F811 redefinition of unused 'EveCharacter' from line 14
opcalendar/models.py:433:20: F821 undefined name 'TokenInvalidError'
opcalendar/models.py:436:20: F821 undefined name 'TokenExpiredError'
opcalendar/models.py:500:5: F811 redefinition of unused '__str__' from line 494
```

Muted errors

```
opcalendar/tasks.py:251:42: W605 invalid escape sequence '\('
opcalendar/tasks.py:251:44: W605 invalid escape sequence '\['
opcalendar/tasks.py:251:51: W605 invalid escape sequence '\)'
opcalendar/tasks.py:251:53: W605 invalid escape sequence '\]'
```